repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-ast
    -   id: debug-statements
    -   id: fix-byte-order-marker
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: mixed-line-ending

-   repo: local
    hooks:
    -   id: unittest
        name: running unittests
        entry: poetry run coverage run -m unittest discover -s tests -p 'test_*.py'
        language: system
        types: [python]
        pass_filenames: false
    -   id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
    -   id: black
        name: black
        entry: poetry run black --check .
        language: system
        types: [python]
    -   id: flake8
        name: flake8
        entry: poetry run flake8
        language: system
        types: [python]
    -   id: pylint
        name: pylint
        entry: poetry run pylint
        language: system
        types: [python]
        args:
          [
            "-rn",
            "-sn",
            "src/*"
          ]
        pass_filenames: false
    -   id: vulture
        name: vulture
        entry: poetry run vulture
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
        args: [
            "src/",
            "tests/"
        ]
    -   id: pydocstyle
        name: pydocstyle
        entry: poetry run pydocstyle src/
        language: system
        require_serial: true
        types: [python]
    -   id: mypy
        name: mypy
        entry: poetry run mypy --strict --disallow-untyped-defs --disallow-incomplete-defs
        args: ["src/"]
        language: system
        pass_filenames: false
    -   id: ruffus
        name: ruff
        entry: poetry run ruff check
        language: system
        types: [python]
        pass_filenames: false
